/* Generated By:JavaCC: Do not edit this line. Assignment5Constants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface Assignment5Constants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int IGNORE = 1;
  /** RegularExpression Id. */
  int CHARACTER = 3;
  /** RegularExpression Id. */
  int RESERVED_WORD = 4;
  /** RegularExpression Id. */
  int SPECIAL_SYMBOL = 5;
  /** RegularExpression Id. */
  int IDENTIFIER = 6;
  /** RegularExpression Id. */
  int LETTER = 7;
  /** RegularExpression Id. */
  int DIGIT = 8;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<IGNORE>",
    "<token of kind 2>",
    "<CHARACTER>",
    "<RESERVED_WORD>",
    "<SPECIAL_SYMBOL>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
  };

}
